### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by magick93** [redhat-developer/s2i-dotnetcore#226]
Hello

I'm getting the following error when building using:

`s2i build . mydockerrepo:5000/dotnet-21-centos7 ${params.Project} -e DOTNET_STARTUP_PROJECT=${params.Project}/${params.Project}.csproj --pull-policy=always DOTNET_RM_SRC=true`

# Error

```
---> Running application ...
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled Exception: System.Net.Sockets.SocketException: Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at MyCo.Product.Api.Program.Main(String[] args) in /opt/app-root/src/MyCo.Product.Api/Program.cs:line 16
```

**Comment by jerboaa** [comment]
It looks like your app is starting kestrel on a privileged port? Since you're using a customized image `mydockerrepo:5000/dotnet-21-centos7` there is not much we can do to help.

**Comment by magick93** [comment]
Its not a customized image - its just pushed to a local registry.

> It looks like your app is starting kestrel on a privileged port?

What is a privilege port? What port should it start on?

**Comment by jerboaa** [comment]
A privileged port is some port number less than 1024. I'd suggest that kestrel starts on 8080 which is exposed from the container:
https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.1/runtime/Dockerfile#L5

**Comment by tmds** [comment]
The s2i image sets `ASPNETCORE_URLS` to `http://*:8080`. This makes Kestrel bind to port 8080 by default.
If your app is trying to use a different port, perhaps you have overridden the port where you build your webhost (`WebHostBuilder`).

**Comment by magick93** [comment]
Thanks, yes it was a port issue. The permission denied error really through me - I thought it was something to do with `fix-permissions`
