### ISSUE TITLE
How to add certificate to user certificate store?

### ISSUE THREAD

**Issue by askids** [redhat-developer/s2i-dotnetcore#368]
hi

I am trying to use IBM MQ .Net Standard library with TLS in a .Net Core 3.1 WebAPI that will be hosted on OCP. For using TLS with IBM MQ library, it will only let us use choose certificate from either System Certificate store or User Certificate Store only.

I tried adding the certificate the typical windows way (it works on Windows).

```
var store = new X509Store(StoreName.My, StoreLocation.CurrentUser); 
store.Open(OpenFlags.ReadWrite); 
store.Add(myAppCert);
```

But I get below error, when the add statement is run on Openshift container.

```
System.Security.Cryptography.CryptographicException: The owner of '/opt/app-root/.dotnet/corefx/cryptography/x509stores/my' is not the current user.
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.EnsureDirectoryPermissions(String path, UInt32 userId) in /_/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 355
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.AddCertToStore(ICertificatePal certPal) in /_/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 141
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal) in /_/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs:line 121
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate) in /_/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Store.cs:line 162
```

Can you please let me know how do I add the certificate file (pfx) to either User or System Certificate store?

Thanks!

**Comment by tmds** [comment]
@askids great!

I've opened https://github.com/redhat-developer/s2i-dotnetcore/issues/369 to track removal of the developer certificate.
